### ISSUE TITLE
이슈 오픈

### ISSUE THREAD

**Issue by keepinmindsh** [miknieyh/calendar#1]
- 선택된 날짜 표기
   -> 선택된 날짜 항목 필요 
- 국경일 조회 
- 기간 선택된 것에 대해서 출력 
- 코드 구조 분리 필요 [ 컴포넌트 분리 코드 작성할 것! ]

**Comment by keepinmindsh** [comment]
- 선택된 날짜 표기 완료 
- 기간 선택된 출력 완료 확인 
- Pre / Next 
- Vuex 상태관리 도입

**Comment by miknieyh** [comment]
- 선택된 날짜 표기 완료 
- 국경일 조회 완료
- 기간에 선택된 것에 대해서 출력 완료
- 코드 구조 분리 완료
