### ISSUE TITLE
Code Review For Calendar

### ISSUE THREAD

**Issue by keepinmindsh** [miknieyh/calendar#2]
- html markup 구조를 깔끔하게 정리 / 구조적인 depth를 필요로 한다!

<span>
  <button class="btn fw-bolder text-black" @click="updateClickDate({date})">
       {{ date.date }}
  </button>
</span>

- 코드 간의 여백 관리 
6-new Date(state.currentYear,state.currentMonthInNumber,lastDayOfCurrentMonth).getDay();

- 가독성
if 문이 너무 길어지면 잘 보이지 않음. 코드 읽기가 어려움 

curDate.getFullYear().toString() + "-" + (curDate.getMonth() + 1).toString() + "-" + curDate.getDate().toString()
            === NationalDate.getFullYear().toString() + "-" + NationalDate.getMonth().toString() + "-" + NationalDate.getDate().toString()

-> getBoolCompareBetweenCurDateAndNationalDate()

- if 작성시 else 없이 작성으로 변경 

- "년 " -> const YEAR_NAME = "년 ";

**Comment by keepinmindsh** [comment]
.env 파일내에서 url 등은 로컬/검증/운영에 맞춰서 모두 구성이 필요함.

**Comment by keepinmindsh** [comment]
console.log 제거 필요

**Comment by miknieyh** [comment]
코드 여백조정, 가독성을위해 if문을 자체함수로 대체, else 삭제
